repos:
  - repo: local
    hooks:
      - id: usort
        name: Formatter
        entry: bash -c 'black -l 79 "$@"; git add -u' --
        language: python
        files: \.py$

  - repo: local
    hooks:
      - id: usort
        name: Sorting import statements
        entry: bash -c 'usort format "$@"; git add -u' --
        language: python
        files: \.py$